version: "2"
services:

  prestashop:
    image: prestashop/prestashop:1.7
    environment:
    - DB_SERVER=bdd
    ports:
    - 8080:80
    depends_on:
    - bdd

  bdd:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=admin